modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/custommobsforge/issues"

[[mods]]
modId="custommobsforge_server"
version="1.0.0"
displayName="CustomMobsForge Server"
description="Server module for CustomMobsForge mod."
authors="YourName"

[[dependencies.custommobsforge_server]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.custommobsforge_server]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="SERVER"

[[dependencies.custommobsforge_server]]
modId="custommobsforge_common"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"